version: "3.8"

services:
  django:
    build: .
    stdin_open: true # interactive
    tty: true # interactive
    command: gunicorn epic_events_crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
      - django_p12_log:/app/log/:rw
      - django_p12_flake8:/app/flake_rapport/:rw
      - django_p12_coverage:/app/htmlcov/:rw
    ports:
      - 80:8000
    env_file:
      - ./.env

volumes:
  static:
  django_p12_log:
  django_p12_flake8:
  django_p12_coverage:
