version: "3.8"

services:
  ocr_p12:
    build: .
    command: gunicorn epic_events_crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
    ports:
      - 80:8000
    env_file:
      - ./.env

volumes:
  static:
