# Generated by Django 4.0.3 on 2022-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=256, unique=True, verbose_name='email'), max_length=128),
        ),
    ]
