# Generated by Django 4.0.3 on 2022-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('MANAGE', 'Manage'), ('SALES', 'Sales'), ('SUPPORT', 'Support')], default='SALES', max_length=30, verbose_name='Profile'),
        ),
    ]
