# Generated by Django 4.0.3 on 2022-03-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_role_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, choices=[('MANAGE', 'Manage'), ('SALES', 'Sales'), ('SUPPORT', 'Support')], max_length=30, null=True, verbose_name='Profile Staff')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Profile_Staff', to='authentication.profilestaff', verbose_name='Profile Staff'),
        ),
    ]
