# Generated by Django 4.0.3 on 2022-03-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profilestaff_alter_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profile_staff',
        ),
    ]
