# Generated by Django 4.0.3 on 2022-03-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_profile_user_profile_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestaff',
            name='profile',
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='manage_staff_acces',
            field=models.BooleanField(default=False, verbose_name='Manage Staff Access'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='manage_staff_create_user',
            field=models.BooleanField(default=False, verbose_name='Staff - Create User'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='manage_staff_delete_user',
            field=models.BooleanField(default=False, verbose_name='Staff - Delete User'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='manage_staff_read_user',
            field=models.BooleanField(default=False, verbose_name='Staff - Read User'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='manage_staff_update_user',
            field=models.BooleanField(default=False, verbose_name='Staff - Update User'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='name',
            field=models.CharField(default='Null', max_length=30, verbose_name='Name Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Profile_Staff_name', to='authentication.profilestaff', verbose_name='Profile Staff Name'),
        ),
    ]
