# Generated by Django 4.0.3 on 2022-03-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_profilestaff_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestaff',
            name='manage_staff_acces',
        ),
    ]
