# Generated by Django 4.0.3 on 2022-03-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_profilestaff_manage_staff_acces'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestaff',
            name='contract_create',
            field=models.BooleanField(default=False, verbose_name='Contract - Create'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='contract_delete',
            field=models.BooleanField(default=False, verbose_name='Contract - Delete'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='contract_read',
            field=models.BooleanField(default=False, verbose_name='Contract - Read'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='contract_update',
            field=models.BooleanField(default=False, verbose_name='Contract - Update'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_create',
            field=models.BooleanField(default=False, verbose_name='Customer - Create'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_delete',
            field=models.BooleanField(default=False, verbose_name='Customer - Delete'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_read',
            field=models.BooleanField(default=False, verbose_name='Customer - Read'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_update',
            field=models.BooleanField(default=False, verbose_name='Customer - Update'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='name',
            field=models.CharField(default='Null', max_length=30, verbose_name='Name Profile'),
        ),
    ]
