# Generated by Django 4.0.3 on 2022-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestaff',
            name='contract_create',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='contract_delete',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='contract_read',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='contract_update',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='customer_create',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='customer_delete',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='customer_read',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='customer_update',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='event_create',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='event_delete',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='event_read',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='event_update',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='manage_staff_create_user',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='manage_staff_delete_user',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='manage_staff_read_user',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='manage_staff_update_user',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='need_create',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='need_delete',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='need_read',
        ),
        migrations.RemoveField(
            model_name='profilestaff',
            name='need_update',
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='contract_CRUD_all',
            field=models.BooleanField(default=False, verbose_name='Contract - CRUD method for all'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='contract_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Contract - CRU method for assigned user'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_CRUD_all',
            field=models.BooleanField(default=False, verbose_name='Customer - CRUD method for all '),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Customer - CRU method for assigned user'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='event_CRUD_all',
            field=models.BooleanField(default=False, verbose_name='Event - CRUD method for all'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='event_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Event - CRU method for assigned user'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='manage_staff_user_crud',
            field=models.BooleanField(default=False, verbose_name='Manage Staff - CRUD method for User'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='need_CRUD_all',
            field=models.BooleanField(default=False, verbose_name='Need - CRUD method for all'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='need_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Need - CRU method for assigned user'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name Profile'),
        ),
    ]
