# Generated by Django 4.0.3 on 2022-04-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_profilestaff_contract_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestaff',
            name='contract_read',
            field=models.BooleanField(default=False, verbose_name='Contract - Read'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='customer_read',
            field=models.BooleanField(default=False, verbose_name='Customer - Read'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='event_read',
            field=models.BooleanField(default=False, verbose_name='Event - Read'),
        ),
        migrations.AddField(
            model_name='profilestaff',
            name='need_read',
            field=models.BooleanField(default=False, verbose_name='Need - Read'),
        ),
    ]
