# Generated by Django 4.0.3 on 2022-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_profilestaff_contract_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestaff',
            name='contract_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Contract - CRU method for Customer.sales_contact assigned'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='contract_read',
            field=models.BooleanField(default=False, verbose_name='Contract - Read only'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='customer_CRUD_all',
            field=models.BooleanField(default=False, verbose_name='Customer - CRUD '),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='customer_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Customer - CRU method for Customer.sales_contact assigned'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='event_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Event - CRU method for Event.support_contact assigned'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='event_read',
            field=models.BooleanField(default=False, verbose_name='Event - Read only'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='manage_staff_user_crud',
            field=models.BooleanField(default=False, verbose_name='Manage Staff - CRUD method for User & Profile_staff'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='need_CRUD_all',
            field=models.BooleanField(default=False, verbose_name='Need - CRUD method'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='need_CRU_assigned',
            field=models.BooleanField(default=False, verbose_name='Need - CRU method for Event.support_contact assigned'),
        ),
        migrations.AlterField(
            model_name='profilestaff',
            name='need_read',
            field=models.BooleanField(default=False, verbose_name='Need - Read only'),
        ),
    ]
