# Generated by Django 4.0.3 on 2022-03-29 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Date Start Contract')),
                ('date_finished', models.DateTimeField(verbose_name='Date End Contract')),
                ('signed', models.BooleanField(default=False, verbose_name='signed')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Title Event')),
                ('date_created', models.DateTimeField(verbose_name='Date Start')),
                ('date_updated', models.DateTimeField(verbose_name='Date Updated')),
                ('date_finished', models.DateTimeField(verbose_name='Date End')),
                ('contract_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contract')),
                ('support_contact', models.ForeignKey(limit_choices_to={'profile_staff': 'SUPPORT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'profile_staff': 'SALES'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title Need')),
                ('success', models.BooleanField(default=False, verbose_name='signed')),
                ('date_updated', models.DateTimeField(verbose_name='Date Updated')),
                ('event_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event')),
                ('support_contact', models.ForeignKey(limit_choices_to={'profile_staff': 'SUPPORT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
