# Generated by Django 4.0.3 on 2022-03-31 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_need_support_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Start Contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_finished',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date End Contract'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='need',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
    ]
