# Generated by Django 4.0.3 on 2022-04-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_contract_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='date_finished',
            new_name='date_end_contract',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_created',
            new_name='date_start_contract',
        ),
    ]
