# Generated by Django 4.0.3 on 2022-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_date_finished_contract_date_end_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='Titlte Contract', max_length=125, verbose_name='Title Contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end_contract',
            field=models.DateTimeField(verbose_name='Date End Contract'),
        ),
    ]
