# Generated by Django 4.0.3 on 2022-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_contract_title_alter_contract_date_end_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(default='Title Contract', max_length=125, verbose_name='Title Contract'),
        ),
        migrations.AlterField(
            model_name='need',
            name='success',
            field=models.BooleanField(default=False, verbose_name='success'),
        ),
    ]
