# Generated by Django 4.0.3 on 2022-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_contract_id_alter_contract_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_start_contract',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Start Contract'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='need',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Updated'),
        ),
    ]
