# Generated by Django 4.0.3 on 2022-04-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_created',
            new_name='date_started',
        ),
    ]
