# Generated by Django 4.0.3 on 2022-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_date_created_event_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_start_contract',
            field=models.DateTimeField(verbose_name='Date Start Contract'),
        ),
    ]
