# Generated by Django 4.0.3 on 2022-04-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_contract_date_start_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_started',
            field=models.DateTimeField(verbose_name='Date Start'),
        ),
    ]
