# Generated by Django 4.0.3 on 2022-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.CharField(default='$', max_length=10, verbose_name='Amount in $'),
        ),
    ]
